export * from "./hero";
export * from "./projects"
export * from "./skills-scroll"
export * from './about'
export * from './header'
export * from './services'
export * from './experience'
export * from './testimonials'
export * from './blog'
export * from './contact'
export * from './footer'